# Generated by Django 3.1 on 2020-09-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldata',
            name='Result',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='bloodPressure',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='diabetesPedigreeFunction',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='glucose',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='insulin',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='patientName',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='pregnancies',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='skinThickness',
        ),
        migrations.RemoveField(
            model_name='medicaldata',
            name='users',
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
