# Generated by Django 3.1 on 2020-09-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20200909_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldata',
            old_name='diabetesPedigreeFunction',
            new_name='diabetesPedgreeFunction',
        ),
    ]
