# Generated by Django 3.1 on 2020-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0014_auto_20200918_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='DOB',
            field=models.CharField(default='Date Of Birth', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='City', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='companyAddress',
            field=models.CharField(default='Company Address', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Country', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='About Me', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobRole',
            field=models.CharField(default='Job Role', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobileNumber',
            field=models.CharField(default='Mobile Number', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipCode',
            field=models.CharField(default='ZIP Code', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='companyName',
            field=models.CharField(default='Company Name', max_length=256, null=True),
        ),
    ]
