# Generated by Django 3.1 on 2020-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0016_userprofile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='companyAddress',
            field=models.CharField(default='Hospital Address', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='companyName',
            field=models.CharField(default='Hospital Name', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='Hospital Description', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='Representative Name', max_length=256, null=True),
        ),
    ]
