# Generated by Django 3.1 on 2020-09-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20200909_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldata',
            old_name='user',
            new_name='owner',
        ),
    ]
