# Generated by Django 3.1 on 2020-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20200909_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='Result',
            field=models.IntegerField(null=True),
        ),
    ]
