# Generated by Django 3.1 on 2020-09-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_medicaldata_patientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldata',
            old_name='Result',
            new_name='result',
        ),
    ]
