# Generated by Django 3.1 on 2020-09-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0015_auto_20200918_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='Full Name', max_length=256, null=True),
        ),
    ]
